- name: setting up the {{ component }}-{{ env }}
  ansible.builtin.package:
    name: nginx
    state: present

- name: copying nginx proxy file
  ansible.builtin.template:
    src: expense.conf
    dest: "{{ proxy_path }}"

- name: copying nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    
# Importing a specific task from common role
- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.import_role:
    name: common
    tasks_from: pre-req

- name: Restarting {{ component }} service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes