- name: Installing {{ component }}-{{ env }}
  ansible.builtin.package:
    name: mysql-server
    state: present
  
- name: Starting {{ component }} service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes 

- name: Resetting root password 
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ MYSQL_PASSWORD }}